-- ============================================
-- User Settings - LOCAL ONLY
-- ============================================
-- Language and Theme settings are stored locally only
-- using SharedPreferences. No database table needed.
-- 
-- This approach provides:
-- 1. Instant UI updates without network latency
-- 2. Works offline
-- 3. No sync conflicts
-- 4. Simpler architecture
--
-- Settings stored locally:
-- - language_code (en/ar)
-- - is_dark_mode (true/false)
-- - notifications_enabled (true/false)
-- - video_autoplay (true/false)
-- ============================================

-- If you previously created the user_settings table,
-- you can drop it with:
-- DROP TABLE IF EXISTS public.user_settings CASCADE;
